documentation:
  container_name: documentation
  image: jrwthll/documentation-dockerfiles:1.3
#  env_file:
#    - common.env
#  links:
#    - adapter
#  volumes_from: 
#    - adapter-data
  ports:
  # port 80 reserved for adapter
     - 83:80
